import Foundation
import Testing

@testable import ShikkiKit

// MARK: - tmTheme Generation Tests

@Suite("tmTheme Generation")
struct TmThemeGenerationTests {

    @Test("Generated XML contains correct background from Dracula theme")
    func tmThemeContainsBackground() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.contains("<key>background</key><string>#282a36</string>"))
    }

    @Test("Generated XML contains correct foreground from Dracula theme")
    func tmThemeContainsForeground() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.contains("<key>foreground</key><string>#f8f8f2</string>"))
    }

    @Test("Generated XML contains correct caret from Dracula theme")
    func tmThemeContainsCaret() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.contains("<key>caret</key><string>#f8f8f2</string>"))
    }

    @Test("Generated XML contains correct selection from Dracula theme")
    func tmThemeContainsSelection() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.contains("<key>selection</key><string>#44475a</string>"))
    }

    @Test("Generated XML contains correct lineHighlight from Dracula theme")
    func tmThemeContainsLineHighlight() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.contains("<key>lineHighlight</key><string>#3a3c4e</string>"))
    }

    @Test("Generated XML has auto-generated header comment")
    func tmThemeHasHeaderComment() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.contains("<!-- Auto-generated by shikki"))
        #expect(xml.contains("do not edit -->"))
    }

    @Test("Generated XML contains all 7 scope rules")
    func tmThemeContainsAllScopeRules() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        let expectedScopes = [
            "comment",
            "string",
            "keyword",
            "constant.numeric",
            "entity.name",
            "variable",
            "support",
        ]
        for scope in expectedScopes {
            #expect(xml.contains("<key>scope</key><string>\(scope)</string>"),
                    "Missing scope rule: \(scope)")
        }
    }

    @Test("Generated XML maps comment scope to base03")
    func tmThemeCommentColor() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        // base03 for Dracula is 6272a4
        #expect(xml.contains("<string>comment</string>"))
        #expect(xml.contains("#6272a4"))
    }

    @Test("Generated XML maps string scope to base0B")
    func tmThemeStringColor() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        // base0B for Dracula is 50fa7b
        #expect(xml.contains("<string>string</string>"))
        #expect(xml.contains("#50fa7b"))
    }

    @Test("Generated XML maps keyword scope to base0E")
    func tmThemeKeywordColor() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        // base0E for Dracula is bd93f9
        #expect(xml.contains("<string>keyword</string>"))
        #expect(xml.contains("#bd93f9"))
    }

    @Test("Tokyo Night theme produces different colors than Dracula")
    func tmThemeDifferentPerTheme() {
        let draculaXml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        let tokyoXml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.tokyoNight)
        // Background should differ
        #expect(draculaXml.contains("#282a36"))
        #expect(tokyoXml.contains("#1a1b26"))
        #expect(!draculaXml.contains("#1a1b26"))
    }

    @Test("Generated XML is valid plist structure")
    func tmThemeIsValidPlist() {
        let xml = ThemeConfigManager.generateTmTheme(from: InlineBuiltInThemes.dracula)
        #expect(xml.hasPrefix("<?xml version=\"1.0\""))
        #expect(xml.contains("<!DOCTYPE plist"))
        #expect(xml.contains("<plist version=\"1.0\">"))
        #expect(xml.contains("</plist>"))
    }
}

// MARK: - Theme Listing Tests

@Suite("Theme Listing")
struct ThemeListingTests {

    @Test("3 built-in themes returned")
    func builtInThemeCount() {
        let themes = ThemeConfigManager.listAllThemes(themesDir: "/nonexistent")
        #expect(themes.count == 3)
    }

    @Test("All built-in themes marked as built-in")
    func allBuiltInFlagged() {
        let themes = ThemeConfigManager.listAllThemes(themesDir: "/nonexistent")
        for entry in themes {
            #expect(entry.isBuiltIn)
        }
    }

    @Test("Built-in theme slugs are correct")
    func builtInSlugs() {
        let themes = ThemeConfigManager.listAllThemes(themesDir: "/nonexistent")
        let slugs = themes.map { $0.theme.slug }
        #expect(slugs.contains("dracula"))
        #expect(slugs.contains("catppuccin-mocha"))
        #expect(slugs.contains("tokyo-night"))
    }

    @Test("Active theme defaults to dracula when no config")
    func defaultActiveTheme() {
        let active = ThemeConfigManager.readActiveThemeName(configPath: "/nonexistent/config.yaml")
        #expect(active == nil) // nil means fallback to dracula
    }

    @Test("Active theme read from config file")
    func activeThemeFromConfig() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let configPath = tmpDir.appendingPathComponent("config.yaml").path
        try "theme: tokyo-night\n".write(toFile: configPath, atomically: true, encoding: .utf8)

        let active = ThemeConfigManager.readActiveThemeName(configPath: configPath)
        #expect(active == "tokyo-night")
    }

    @Test("Custom themes loaded from themes directory")
    func customThemesLoaded() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        // Write a valid Base16 YAML theme
        let themeContent = """
        scheme: "Nord"
        base00: "2e3440"
        base01: "3b4252"
        base02: "434c5e"
        base03: "4c566a"
        base04: "d8dee9"
        base05: "e5e9f0"
        base06: "eceff4"
        base07: "8fbcbb"
        base08: "bf616a"
        base09: "d08770"
        base0A: "ebcb8b"
        base0B: "a3be8c"
        base0C: "88c0d0"
        base0D: "81a1c1"
        base0E: "b48ead"
        base0F: "5e81ac"
        """
        try themeContent.write(
            toFile: tmpDir.appendingPathComponent("nord.yaml").path,
            atomically: true,
            encoding: .utf8
        )

        let themes = ThemeConfigManager.listAllThemes(themesDir: tmpDir.path)
        #expect(themes.count == 4) // 3 built-in + 1 custom
        let custom = themes.first(where: { $0.theme.slug == "nord" })
        #expect(custom != nil)
        #expect(custom?.isBuiltIn == false)
        #expect(custom?.theme.name == "Nord")
    }

    @Test("Swatch renders 16 colored blocks")
    func swatchRendering() {
        let swatch = ThemeConfigManager.renderSwatch(InlineBuiltInThemes.dracula)
        // Each slot = ansiBg (variable length) + "  " (2 spaces), then reset at end
        // Count the "  " segments — should have 16
        let stripped = swatch.replacingOccurrences(
            of: "\u{1B}\\[[0-9;]*m",
            with: "",
            options: .regularExpression
        )
        #expect(stripped == String(repeating: "  ", count: 16))
    }
}

// MARK: - Config Update Tests

@Suite("Config Update")
struct ConfigUpdateTests {

    @Test("Creates config.yaml if missing")
    func createsConfigIfMissing() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let configPath = tmpDir.appendingPathComponent("config.yaml").path
        #expect(!FileManager.default.fileExists(atPath: configPath))

        try ThemeConfigManager.setActiveTheme("tokyo-night", configPath: configPath)

        #expect(FileManager.default.fileExists(atPath: configPath))
        let content = try String(contentsOfFile: configPath, encoding: .utf8)
        #expect(content.contains("theme: tokyo-night"))
    }

    @Test("Updates existing theme line")
    func updatesExistingThemeLine() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let configPath = tmpDir.appendingPathComponent("config.yaml").path
        try "theme: dracula\n".write(toFile: configPath, atomically: true, encoding: .utf8)

        try ThemeConfigManager.setActiveTheme("catppuccin-mocha", configPath: configPath)

        let content = try String(contentsOfFile: configPath, encoding: .utf8)
        #expect(content.contains("theme: catppuccin-mocha"))
        #expect(!content.contains("theme: dracula"))
    }

    @Test("Preserves other config lines")
    func preservesOtherLines() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let configPath = tmpDir.appendingPathComponent("config.yaml").path
        let original = """
        telemetry: local
        theme: dracula
        debug: false
        """
        try original.write(toFile: configPath, atomically: true, encoding: .utf8)

        try ThemeConfigManager.setActiveTheme("tokyo-night", configPath: configPath)

        let content = try String(contentsOfFile: configPath, encoding: .utf8)
        #expect(content.contains("telemetry: local"))
        #expect(content.contains("theme: tokyo-night"))
        #expect(content.contains("debug: false"))
        #expect(!content.contains("theme: dracula"))
    }

    @Test("Adds theme line when config exists without one")
    func addsThemeLineWhenMissing() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let configPath = tmpDir.appendingPathComponent("config.yaml").path
        try "telemetry: local\n".write(toFile: configPath, atomically: true, encoding: .utf8)

        try ThemeConfigManager.setActiveTheme("dracula", configPath: configPath)

        let content = try String(contentsOfFile: configPath, encoding: .utf8)
        #expect(content.contains("telemetry: local"))
        #expect(content.contains("theme: dracula"))
    }
}

// MARK: - InlineBase16Color Tests

@Suite("InlineBase16Color")
struct InlineBase16ColorTests {

    @Test("Parse valid hex string")
    func parseValidHex() {
        let color = InlineBase16Color(hex: "bd93f9")
        #expect(color != nil)
        #expect(color?.r == 189)
        #expect(color?.g == 147)
        #expect(color?.b == 249)
    }

    @Test("Parse hex with hash prefix")
    func parseHexWithHash() {
        let color = InlineBase16Color(hex: "#ff5555")
        #expect(color != nil)
        #expect(color?.r == 255)
        #expect(color?.g == 85)
        #expect(color?.b == 85)
    }

    @Test("Reject invalid hex string")
    func rejectInvalidHex() {
        #expect(InlineBase16Color(hex: "zzzzzz") == nil)
        #expect(InlineBase16Color(hex: "abc") == nil)
        #expect(InlineBase16Color(hex: "") == nil)
    }

    @Test("Hex output matches input")
    func hexRoundTrip() {
        let color = InlineBase16Color(hex: "282a36")!
        #expect(color.hex == "282a36")
    }

    @Test("ansiBg produces valid ANSI background escape")
    func ansiBgEscape() {
        let color = InlineBase16Color(r: 40, g: 42, b: 54)
        #expect(color.ansiBg == "\u{1B}[48;2;40;42;54m")
    }
}

// MARK: - Theme Resolution Tests

@Suite("Theme Resolution")
struct ThemeResolutionTests {

    @Test("Resolve built-in theme by slug")
    func resolveBuiltIn() {
        let theme = ThemeConfigManager.resolveTheme("dracula", themesDir: "/nonexistent")
        #expect(theme != nil)
        #expect(theme?.name == "Dracula")
    }

    @Test("Resolve returns nil for unknown slug")
    func resolveUnknown() {
        let theme = ThemeConfigManager.resolveTheme("nonexistent", themesDir: "/nonexistent")
        #expect(theme == nil)
    }

    @Test("All built-in themes have 16 slots")
    func allSlotsPresent() {
        for theme in [InlineBuiltInThemes.dracula, InlineBuiltInThemes.catppuccinMocha, InlineBuiltInThemes.tokyoNight] {
            #expect(theme.allSlots.count == 16)
        }
    }
}

// MARK: - YAML Parser Tests

@Suite("Base16 YAML Parser")
struct Base16YAMLParserTests {

    @Test("Parse valid Base16 YAML file")
    func parseValidYAML() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let content = """
        scheme: "Test Theme"
        base00: "111111"
        base01: "222222"
        base02: "333333"
        base03: "444444"
        base04: "555555"
        base05: "666666"
        base06: "777777"
        base07: "888888"
        base08: "999999"
        base09: "aaaaaa"
        base0A: "bbbbbb"
        base0B: "cccccc"
        base0C: "dddddd"
        base0D: "eeeeee"
        base0E: "ff0000"
        base0F: "00ff00"
        """
        let path = tmpDir.appendingPathComponent("test.yaml").path
        try content.write(toFile: path, atomically: true, encoding: .utf8)

        let theme = ThemeConfigManager.parseBase16YAML(at: path, fallbackSlug: "test")
        #expect(theme != nil)
        #expect(theme?.name == "Test Theme")
        #expect(theme?.slug == "test")
        #expect(theme?.base00.hex == "111111")
        #expect(theme?.base0E.hex == "ff0000")
    }

    @Test("Returns nil when slots are missing")
    func rejectIncompleteYAML() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let content = """
        base00: "111111"
        base01: "222222"
        """
        let path = tmpDir.appendingPathComponent("incomplete.yaml").path
        try content.write(toFile: path, atomically: true, encoding: .utf8)

        let theme = ThemeConfigManager.parseBase16YAML(at: path, fallbackSlug: "incomplete")
        #expect(theme == nil)
    }

    @Test("Falls back to slug when scheme field is absent")
    func fallbackToSlug() throws {
        let tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("shikki-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tmpDir) }

        let content = """
        base00: "111111"
        base01: "222222"
        base02: "333333"
        base03: "444444"
        base04: "555555"
        base05: "666666"
        base06: "777777"
        base07: "888888"
        base08: "999999"
        base09: "aaaaaa"
        base0A: "bbbbbb"
        base0B: "cccccc"
        base0C: "dddddd"
        base0D: "eeeeee"
        base0E: "ff0000"
        base0F: "00ff00"
        """
        let path = tmpDir.appendingPathComponent("no-scheme.yaml").path
        try content.write(toFile: path, atomically: true, encoding: .utf8)

        let theme = ThemeConfigManager.parseBase16YAML(at: path, fallbackSlug: "my-theme")
        #expect(theme != nil)
        #expect(theme?.name == "my-theme")
    }
}
