import Foundation

// MARK: - MotoFile

/// The `.moto` project configuration file.
/// Generated by `shi init`, consumed by the orchestrator and agents.
/// YAML-like format stored as structured data, serialized to TOML-style plain text.
public struct MotoFile: Codable, Sendable, Equatable {
    public var name: String
    public var language: String
    public var framework: String?
    public var buildSystem: String?
    public var testCommand: String?
    public var buildCommand: String?
    public var lintCommand: String?

    /// Architecture conventions for the project.
    public var architecture: Architecture?

    /// Agent-specific settings.
    public var agents: AgentSettings?

    public init(
        name: String,
        language: String,
        framework: String? = nil,
        buildSystem: String? = nil,
        testCommand: String? = nil,
        buildCommand: String? = nil,
        lintCommand: String? = nil,
        architecture: Architecture? = nil,
        agents: AgentSettings? = nil
    ) {
        self.name = name
        self.language = language
        self.framework = framework
        self.buildSystem = buildSystem
        self.testCommand = testCommand
        self.buildCommand = buildCommand
        self.lintCommand = lintCommand
        self.architecture = architecture
        self.agents = agents
    }

    // MARK: - Nested Types

    public struct Architecture: Codable, Sendable, Equatable {
        public var pattern: String?           // e.g. "MVVM", "Clean", "MVC"
        public var sourceRoot: String?        // e.g. "Sources", "src"
        public var testRoot: String?          // e.g. "Tests", "tests"
        public var modules: [String]?         // e.g. ["Core", "UI", "Network"]

        public init(
            pattern: String? = nil,
            sourceRoot: String? = nil,
            testRoot: String? = nil,
            modules: [String]? = nil
        ) {
            self.pattern = pattern
            self.sourceRoot = sourceRoot
            self.testRoot = testRoot
            self.modules = modules
        }
    }

    public struct AgentSettings: Codable, Sendable, Equatable {
        public var maxConcurrency: Int?
        public var budgetDailyUSD: Double?
        public var preferredModel: String?

        public init(
            maxConcurrency: Int? = nil,
            budgetDailyUSD: Double? = nil,
            preferredModel: String? = nil
        ) {
            self.maxConcurrency = maxConcurrency
            self.budgetDailyUSD = budgetDailyUSD
            self.preferredModel = preferredModel
        }
    }
}

// MARK: - Factory

extension MotoFile {

    /// Create a MotoFile from a DetectedProject.
    public static func from(detected: DetectedProject) -> MotoFile {
        MotoFile(
            name: detected.name,
            language: detected.language.rawValue,
            framework: detected.framework?.rawValue,
            buildSystem: detected.buildSystem?.rawValue,
            testCommand: defaultTestCommand(for: detected),
            buildCommand: defaultBuildCommand(for: detected),
            lintCommand: defaultLintCommand(for: detected),
            architecture: defaultArchitecture(for: detected),
            agents: AgentSettings(maxConcurrency: 3, budgetDailyUSD: 10.0)
        )
    }

    private static func defaultTestCommand(for project: DetectedProject) -> String? {
        switch project.buildSystem {
        case .spm: "swift test"
        case .xcodebuild: "xcodebuild test"
        case .npm, .yarn, .pnpm: "npm test"
        case .cargo: "cargo test"
        case .goMod: "go test ./..."
        case .gradle: "./gradlew test"
        case .maven: "mvn test"
        case .bundler: "bundle exec rspec"
        case .pip, .poetry: "pytest"
        case nil: nil
        }
    }

    private static func defaultBuildCommand(for project: DetectedProject) -> String? {
        switch project.buildSystem {
        case .spm: "swift build"
        case .xcodebuild: "xcodebuild build"
        case .npm: "npm run build"
        case .yarn: "yarn build"
        case .pnpm: "pnpm build"
        case .cargo: "cargo build"
        case .goMod: "go build ./..."
        case .gradle: "./gradlew build"
        case .maven: "mvn package"
        case .bundler: nil
        case .pip, .poetry: nil
        case nil: nil
        }
    }

    private static func defaultLintCommand(for project: DetectedProject) -> String? {
        switch project.language {
        case .swift: "swiftlint"
        case .typescript: "npx eslint ."
        case .python: "ruff check ."
        case .rust: "cargo clippy"
        case .go: "golangci-lint run"
        case .ruby: "rubocop"
        case .kotlin, .java: nil
        case .unknown: nil
        }
    }

    private static func defaultArchitecture(for project: DetectedProject) -> Architecture? {
        let sourceRoot: String?
        let testRoot: String?

        switch project.language {
        case .swift:
            sourceRoot = "Sources"
            testRoot = "Tests"
        case .typescript:
            sourceRoot = "src"
            testRoot = "tests"
        case .python:
            sourceRoot = project.name.lowercased().replacingOccurrences(of: " ", with: "_")
            testRoot = "tests"
        case .rust:
            sourceRoot = "src"
            testRoot = "tests"
        case .go:
            sourceRoot = "."
            testRoot = "."
        case .ruby:
            sourceRoot = "lib"
            testRoot = "spec"
        case .kotlin, .java:
            sourceRoot = "src/main"
            testRoot = "src/test"
        case .unknown:
            return nil
        }

        return Architecture(
            sourceRoot: sourceRoot,
            testRoot: testRoot
        )
    }
}

// MARK: - Serialization

extension MotoFile {

    /// Serialize to a human-readable TOML-like `.moto` format.
    public func serialize() -> String {
        var lines: [String] = []

        lines.append("# Shikki project configuration")
        lines.append("# Generated by `shi init`")
        lines.append("")
        lines.append("[project]")
        lines.append("name = \"\(name)\"")
        lines.append("language = \"\(language)\"")

        if let framework {
            lines.append("framework = \"\(framework)\"")
        }
        if let buildSystem {
            lines.append("build_system = \"\(buildSystem)\"")
        }

        lines.append("")
        lines.append("[commands]")
        if let testCommand {
            lines.append("test = \"\(testCommand)\"")
        }
        if let buildCommand {
            lines.append("build = \"\(buildCommand)\"")
        }
        if let lintCommand {
            lines.append("lint = \"\(lintCommand)\"")
        }

        if let arch = architecture {
            lines.append("")
            lines.append("[architecture]")
            if let pattern = arch.pattern {
                lines.append("pattern = \"\(pattern)\"")
            }
            if let sourceRoot = arch.sourceRoot {
                lines.append("source_root = \"\(sourceRoot)\"")
            }
            if let testRoot = arch.testRoot {
                lines.append("test_root = \"\(testRoot)\"")
            }
            if let modules = arch.modules, !modules.isEmpty {
                let quoted = modules.map { "\"\($0)\"" }.joined(separator: ", ")
                lines.append("modules = [\(quoted)]")
            }
        }

        if let agents {
            lines.append("")
            lines.append("[agents]")
            if let maxConcurrency = agents.maxConcurrency {
                lines.append("max_concurrency = \(maxConcurrency)")
            }
            if let budget = agents.budgetDailyUSD {
                lines.append("budget_daily_usd = \(String(format: "%.2f", budget))")
            }
            if let model = agents.preferredModel {
                lines.append("preferred_model = \"\(model)\"")
            }
        }

        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Parse a `.moto` file from its serialized TOML-like format.
    public static func parse(from content: String) -> MotoFile? {
        var name = ""
        var language = ""
        var framework: String?
        var buildSystem: String?
        var testCommand: String?
        var buildCommand: String?
        var lintCommand: String?
        var archPattern: String?
        var archSourceRoot: String?
        var archTestRoot: String?
        var archModules: [String]?
        var agentMaxConcurrency: Int?
        var agentBudget: Double?
        var agentModel: String?

        var currentSection = ""

        for line in content.split(separator: "\n", omittingEmptySubsequences: false) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }

            if trimmed.hasPrefix("[") && trimmed.hasSuffix("]") {
                currentSection = String(trimmed.dropFirst().dropLast())
                continue
            }

            let parts = trimmed.split(separator: "=", maxSplits: 1)
            guard parts.count == 2 else { continue }
            let key = parts[0].trimmingCharacters(in: .whitespaces)
            let rawValue = parts[1].trimmingCharacters(in: .whitespaces)
            let value = stripQuotes(rawValue)

            switch currentSection {
            case "project":
                switch key {
                case "name": name = value
                case "language": language = value
                case "framework": framework = value
                case "build_system": buildSystem = value
                default: break
                }
            case "commands":
                switch key {
                case "test": testCommand = value
                case "build": buildCommand = value
                case "lint": lintCommand = value
                default: break
                }
            case "architecture":
                switch key {
                case "pattern": archPattern = value
                case "source_root": archSourceRoot = value
                case "test_root": archTestRoot = value
                case "modules": archModules = parseArray(rawValue)
                default: break
                }
            case "agents":
                switch key {
                case "max_concurrency": agentMaxConcurrency = Int(value)
                case "budget_daily_usd": agentBudget = Double(value)
                case "preferred_model": agentModel = value
                default: break
                }
            default:
                break
            }
        }

        guard !name.isEmpty, !language.isEmpty else { return nil }

        let arch: Architecture?
        if archPattern != nil || archSourceRoot != nil || archTestRoot != nil || archModules != nil {
            arch = Architecture(
                pattern: archPattern,
                sourceRoot: archSourceRoot,
                testRoot: archTestRoot,
                modules: archModules
            )
        } else {
            arch = nil
        }

        let agents: AgentSettings?
        if agentMaxConcurrency != nil || agentBudget != nil || agentModel != nil {
            agents = AgentSettings(
                maxConcurrency: agentMaxConcurrency,
                budgetDailyUSD: agentBudget,
                preferredModel: agentModel
            )
        } else {
            agents = nil
        }

        return MotoFile(
            name: name,
            language: language,
            framework: framework,
            buildSystem: buildSystem,
            testCommand: testCommand,
            buildCommand: buildCommand,
            lintCommand: lintCommand,
            architecture: arch,
            agents: agents
        )
    }

    private static func stripQuotes(_ s: String) -> String {
        if s.hasPrefix("\"") && s.hasSuffix("\"") && s.count >= 2 {
            return String(s.dropFirst().dropLast())
        }
        return s
    }

    private static func parseArray(_ s: String) -> [String] {
        // Parse [\"a\", \"b\", \"c\"]
        let inner = s.trimmingCharacters(in: .whitespaces)
            .replacingOccurrences(of: "[", with: "")
            .replacingOccurrences(of: "]", with: "")
        return inner.split(separator: ",").map { item in
            stripQuotes(item.trimmingCharacters(in: .whitespaces))
        }
    }
}
